### PR TITLE
WIP: main page  improved

### PR DESCRIPTION
**Pull request by akki111singh**
@aashutoshrathi can u once please check it before i can eslint and beautify it.

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Can you resolve conflicts so that I can check it

**Comment by akki111singh** [comment]
@aashutoshrathi have u checked it ?

**Comment by aashutoshrathi** [comment]
@akki111singh This wasn't issue.

**Comment by aashutoshrathi** [comment]
I have fixed it on real repo.

**Pull request closed without merging**
